import React, { useState } from 'react';
import Navbar from '../Navbar';

function Project1Content() {
    return (
        <div>
            <div style={{
                width: '100%',
                height: '30px',
                border: '2px solid black',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'flex-start',
                background: 'linear-gradient(to right, gray, #a0a0a0)',
                marginBottom: '20px'
            }}>
                <h1 style={{ marginLeft: '10px' }}>Image Augmenter with AWS</h1>
            </div>

            <div>
                <p>Unfortunately, I can't provide the GitHub link for this project due to API keys, but I can demonstrate its functionality with videos and explanations:</p>
                
                <div style={{
                    display: 'flex',
                    justifyContent: 'center',
                    alignItems: 'center',
                    marginTop: '20px'
                }}>
                    <video width="500" controls style={{
                        border: '2px solid black',
                        borderRadius: '8px',
                        marginLeft: '20px' // Moves the video slightly to the right
                    }}>
                        <source src='/Images/2024-06-13 14-33-02.mp4' type='video/mp4' />
                    </video>
                </div>
                
                <p>The application superimposes multiple PNG images onto random backgrounds. The backend is entirely serverless, powered by AWS Lambda, S3, Cognito, and other AWS services.</p>
                
                <p>Here's an overview of the cloud infrastructure setup:</p>
                <img src='/Images/InfrastructureAWSCloud.PNG' style={{
                    display: 'block',
                    width: '100%',
                    maxWidth: '700px',
                    margin: '20px auto',
                    border: '2px solid black',
                    borderRadius: '2%'
                }} alt="AWS Cloud Infrastructure Diagram" />
                
                <p>Users can upload images through a presigned URL generated by a Lambda function after authenticating via an API gateway. Tokens are validated and deducted based on the number and size of uploaded images. Downloading follows a similar process with presigned URLs.</p>
            </div>
        </div>
    );
}


function AllReactProjects() {
    const [selectedProject, setSelectedProject] = useState(null);
    const [showPopup, setShowPopup] = useState(false);

    const handleDownloadClick = () => {
        setShowPopup(true);
    };

    const closePopup = () => {
        setShowPopup(false);
    };

    return (
        <div>
            <Navbar />
            <div style={{
                display: 'flex',
                justifyContent: 'center',
                backgroundColor: '#007f7f',
                minHeight: '100vh',
                padding: '20px',
                position: 'relative',
            }}>
                {/* Projects Panel (Left) */}
                <div style={{
                    width: '250px',
                    height: '180px',
                    backgroundColor: '#c0c0c0',
                    border: '2px solid black',
                    padding: '10px',
                    marginRight: '20px'
                }}>
                    <div style={{
                        display: 'flex',
                        alignItems: 'center',
                        padding: '5px',
                        background: 'linear-gradient(to right, gray, #a0a0a0)',
                        borderBottom: '2px solid black',
                    }}>
                        <img src="/Images/computer_98.png" alt="Project Icon" style={{ width: '25px', height: '25px', marginRight: '10px' }} />
                        <span><u>R</u>eact projects</span>
                    </div>
                    <button onClick={() => setSelectedProject('Project1')} style={buttonStyle}>Project Image Augmenter</button>
                </div>

                {/* Central Content Area */}
                {selectedProject && (
                    <div style={{
                        width: '700px',
                        backgroundColor: '#c0c0c0',
                        border: '2px solid black',
                        padding: '20px',
                        textAlign: 'left'
                    }}>
                        {selectedProject === 'Project1' && <Project1Content />}
                        <button onClick={() => setSelectedProject(null)} style={buttonStyle}>Close</button>
                    </div>
                )}

                {/* Download Section (Right) */}
                {selectedProject && (
                    <div style={{
                        width: '220px',
                        height: '130px',
                        backgroundColor: '#c0c0c0',
                        border: '2px solid black',
                        padding: '10px',
                        marginLeft: '20px'
                    }}>
                        <div style={{
                            display: 'flex',
                            alignItems: 'center',
                            padding: '5px',
                            background: 'linear-gradient(to right, gray, #a0a0a0)',
                            borderBottom: '2px solid black',
                        }}>
                            <img src="/Images/computer_98.png" alt="Download Icon" style={{ width: '25px', height: '25px', marginRight: '10px' }} />
                            <span><u>D</u>ownload Project</span>
                        </div>
                        <p style={{ marginTop: '10px', fontSize: '14px' }}>This will download a zip</p>
                        <button onClick={handleDownloadClick} style={buttonStyle}>
                            <u>D</u>ownload
                        </button>
                    </div>
                )}
            </div>

            {/* Popup Window */}
            {showPopup && (
                <div style={popupOverlayStyle}>
                    <div style={popupWindowStyle}>
                        <div style={popupHeaderStyle}>
                            <span>Download Error</span>
                            <button onClick={closePopup} style={popupCloseButtonStyle}>X</button>
                        </div>
                        <div style={{ padding: '20px', fontSize: '14px' }}>
                            <p>Download not available for this project.</p>
                        </div>
                        <button onClick={closePopup} style={buttonStyle}>OK</button>
                    </div>
                </div>
            )}
        </div>
    );
}

// Styles
const buttonStyle = {
    color: 'black',
    fontSize: '16px',
    padding: '8px',
    backgroundColor: '#c0c0c0',
    cursor: 'pointer',
    width: '100%',
    borderLeftColor: '#FFFFFF',
    borderTopColor: '#FFFFFF',
    borderRightColor: '#000000',
    borderBottomColor: '#000000',
    marginTop: '10px',
};

const popupOverlayStyle = {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
};

const popupWindowStyle = {
    width: '300px',
    backgroundColor: '#c0c0c0',
    border: '2px solid black',
    borderRadius: '5px',
    textAlign: 'center',
};

const popupHeaderStyle = {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'gray',
    padding: '5px 10px',
    borderBottom: '2px solid black',
};

const popupCloseButtonStyle = {
    backgroundColor: 'transparent',
    border: 'none',
    color: 'black',
    cursor: 'pointer',
};

export default AllReactProjects;
